version: '3'
services:
  app:
    build: ./
    ports:
      - "80:8080"
    depends_on:
      - mypostgres
    volumes:
      - "app.jar"
    command: ['java', '-jar', '/app.jar']
  mypostgres:
    image: postgres
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=clickbus